import "dotenv/config";

import { randomUUID } from "node:crypto";

import { prisma } from "../src/lib/db";
import { isModelConfigured } from "../src/modules/ai/agent";
import { handleChatMessage } from "../src/modules/ai/chat";

const RETRY_DELAY_MS = 25_000;

async function sendWithRetry(
  session: { id: string; clinicId: string },
  message: string,
): Promise<void> {
  // Reuse one id across retries so a partial failure never duplicates a message.
  const clientMessageId = randomUUID();
  for (let attempt = 1; attempt <= 4; attempt += 1) {
    try {
      await handleChatMessage(session, { message, clientMessageId });
      return;
    } catch (error) {
      const retryable =
        error instanceof Error && /quota|rate|unavailable|429|503/i.test(error.message);
      if (!retryable || attempt === 4) throw error;
      console.log(
        `  rate limited, waiting ${RETRY_DELAY_MS / 1000}s (attempt ${attempt})…`,
      );
      await new Promise((resolve) => setTimeout(resolve, RETRY_DELAY_MS));
    }
  }
}

/**
 * Creates three realistic visitor conversations. The assistant replies are
 * generated by the configured model (Gemini). This script refuses to run
 * without GEMINI_API_KEY so it never writes keyword-fallback answers.
 */

type Scenario = {
  visitor: { displayName: string; contact: string };
  messages: string[];
};

const SCENARIOS: Scenario[] = [
  {
    visitor: {
      displayName: "Sara Al Mansoori",
      contact: "sara.almansoori@gmail.com",
    },
    messages: [
      "Hi, what are your opening hours on Friday and Saturday?",
      "Can I book a dental cleaning for Saturday morning?",
      "Great, my name is Sara and you can reach me on this email.",
    ],
  },
  {
    visitor: {
      displayName: "James Whitfield",
      contact: "james.whitfield@outlook.com",
    },
    messages: [
      "How much is teeth whitening?",
      "And do you offer Hydrafacial? How long does it take?",
    ],
  },
  {
    visitor: {
      displayName: "Aisha Kareem",
      contact: "aisha.kareem@gmail.com",
    },
    messages: [
      "I need to cancel my appointment, what is your policy?",
      "Actually, could I speak to a staff member about rescheduling?",
    ],
  },
];

async function main() {
  if (!isModelConfigured()) {
    console.error(
      "GEMINI_API_KEY is not set. This script only creates real model replies; add the key to .env and try again.",
    );
    process.exitCode = 1;
    return;
  }

  const clinic = await prisma.clinic.findFirstOrThrow();

  const existing = await prisma.conversation.findMany({
    where: { clinicId: clinic.id },
    select: { id: true },
  });
  const existingIds = existing.map((conversation) => conversation.id);
  const createdIds: string[] = [];

  try {
    for (const scenario of SCENARIOS) {
      const guest = await prisma.guestSession.create({
        data: {
          clinicId: clinic.id,
          tokenHash: randomUUID(),
          expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        },
      });

      await prisma.visitor.create({
        data: {
          clinicId: clinic.id,
          guestSessionId: guest.id,
          displayName: scenario.visitor.displayName,
          contact: scenario.visitor.contact,
          consentAt: new Date(),
        },
      });

      for (const message of scenario.messages) {
        await sendWithRetry({ id: guest.id, clinicId: clinic.id }, message);
        const conversation = await prisma.conversation.findFirst({
          where: { guestSessionId: guest.id },
          orderBy: { createdAt: "desc" },
          select: { id: true },
        });
        if (conversation && !createdIds.includes(conversation.id)) {
          createdIds.push(conversation.id);
        }
        // Space requests to respect the free-tier rate limit.
        await new Promise((resolve) => setTimeout(resolve, 7000));
      }
      console.log(`Created conversation for ${scenario.visitor.displayName}`);
    }

    // Only remove the previous conversations once the new ones are complete.
    if (existingIds.length) {
      await prisma.conversation.deleteMany({
        where: { id: { in: existingIds } },
      });
    }
    console.log(`Done. ${createdIds.length} realistic conversations are ready.`);
  } catch (error) {
    // Roll back partial new conversations so previous data is preserved.
    if (createdIds.length) {
      await prisma.conversation.deleteMany({
        where: { id: { in: createdIds } },
      });
    }
    throw error;
  }
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
